//// Generated by spider on 2020-04-29 12:03:12.033772

class AssetImages {
  static const String noInternet = 'assets/images/no-internet.png';
  static const String statistics = 'assets/images/statistics.png';
  static const String genericError = 'assets/images/generic-error.png';
}
